### ISSUE TITLE
[TODO] v0.0.3

### ISSUE THREAD

**Issue by paithiov909** [paithiov909/conifer#3]
- [ ] escape non ASCII chars in test.date
- [ ] add test for enrichment contact
- [ ] add enrichment convert
- [ ] add transumute convert
- [ ] add tests for them
- [ ] documentation
- [ ] vigenttes (optional)

**Comment by paithiov909** [comment]
IMI components のラッパーは別のプロジェクトに付けることにした
